// AUTO-GENERATED by scripts/generate-docs.ts
// Static resources (rest-api, workflows) are preserved from the previous version.
// Extracted resources are regenerated from website TSX doc pages.
// To regenerate: npm run generate:docs

export interface DocResource {
  uri: string;
  name: string;
  description: string;
  mimeType: string;
  content: string;
}

export const docResources: DocResource[] = [
  {
    uri: "insightsentry://docs/rest-api",
    name: "InsightSentry REST API Guide",
    description: "Complete REST API reference: authentication, base URL, all endpoints with parameters and response formats",
    mimeType: "text/markdown",
    content: `# InsightSentry REST API Guide

## Base URL
\`\`\`
https://api.insightsentry.com
\`\`\`

## Authentication
All requests require a Bearer token obtained from the InsightSentry dashboard (https://insightsentry.com/dashboard).

\`\`\`
Authorization: Bearer <your-api-key>
\`\`\`

## Symbol Format
Symbols use the \`EXCHANGE:SYMBOL\` format. Examples:
- \`NASDAQ:AAPL\` — Apple on NASDAQ
- \`NYSE:TSLA\` — Tesla on NYSE
- \`BINANCE:BTCUSDT\` — Bitcoin/USDT on Binance
- \`CME_MINI:NQ1!\` — E-mini NASDAQ continuous futures
- \`COMEX:GC1!\` — Gold continuous futures
- \`OPRA:AAPL260417P325.0\` — Apple put option

Use the \`search_symbols\` tool to find symbol codes.

## Endpoints Overview

### Time Series & Historical Data
- **GET /v3/symbols/{symbol}/series** — Recent OHLCV data (up to 30k bars) with real-time option
  - Parameters: bar_type (tick/second/minute/hour/day/week/month), bar_interval (1-1440), dp (data points, 1-30000), extended (pre/post market), dadj (dividend adjustment), badj (back-adjustment), settlement, long_poll (wait for real-time), currency (convert to different currency)
- **GET /v3/symbols/{symbol}/history** — Intraday historical data (second/minute/hour, 20+ years for popular exchanges)
  - Parameters: bar_type (second/minute/hour, required), bar_interval, start_date (YYYY-MM or YYYY-MM-DD, required), extended, dadj, badj, settlement
  - Note: Returns one day of data for second bars (YYYY-MM-DD), or one month for minute/hour bars (YYYY-MM). Iterate for longer ranges.

### Symbol Information
- **GET /v3/symbols/{symbol}/info** — Detailed metadata: type, currency, sector, industry, CEO, market cap, P/E, dividends, splits, option chains, all-time high/low, etc.
- **GET /v3/symbols/{symbol}/session** — Trading session details: holidays, trading hours, timezone, session corrections
- **GET /v3/symbols/{symbol}/contracts** — Futures contract list with settlement dates

### Quotes
- **GET /v3/symbols/quotes?codes=...** — Real-time quotes for up to 10 symbols (comma-separated)
  - Returns: last_price, change, change_percent, bid/ask, volume, market_cap, status (OPEN/CLOSED/PRE/POST)

### Search
- **GET /v3/symbols/search** — Search for symbols
  - Parameters: query, type (stock/crypto/futures/forex/etf/bond/index/...), country (2-letter ISO), page
  - Tip: Use \`query=NASDAQ:\` to list all NASDAQ symbols. Leave query empty with type filter to browse.

### Fundamentals
- **GET /v3/symbols/{symbol}/fundamentals** — Comprehensive fundamental data (valuation, profitability, balance sheet, income statement, cash flow)
- **GET /v3/symbols/{symbol}/fundamentals/series?ids=...** — Historical fundamental indicators (max 5 IDs per request). Get available IDs from the fundamentals meta endpoint.
- **GET /v3/symbols/fundamentals** — Metadata: available fundamental/technical indicator IDs and their names

### Options
- **GET /v3/options/list?code=...** — List available option contracts for a symbol
- **GET /v3/options/expiration?code=...&expiration=YYYY-MM-DD** — Option chain by expiration date
- **GET /v3/options/strike?code=...&strike=210** — Option chain by strike price
- Both support sortBy (type/ask_price/bid_price/delta/gamma/implied_volatility/rho/strike_price/theta/vega) and sort (asc/desc)
- Response includes Greeks: delta, gamma, theta, vega, rho, implied_volatility, bid_iv, ask_iv

### Screeners
- **GET /v3/screeners/{type}** — Get available fields, exchanges, countries for a screener type (stock/etf/bond/crypto)
- **POST /v3/screeners/{type}** — Filter instruments with custom criteria
  - Body: { fields: string[] (required, 1-10), exchanges?: string[], countries?: string[], page?: number, sortBy?: string, sortOrder?: "asc"|"desc", ignore_invalid?: boolean }
  - Response: paginated data with requested fields, up to 1000 items per page
  - Note: Crypto screener does not support country filtering

### Calendar
- **GET /v3/calendar/dividends** — Dividend calendar (w: week range, c: country codes)
- **GET /v3/calendar/earnings** — Earnings calendar
- **GET /v3/calendar/ipos** — IPO calendar
- **GET /v3/calendar/events** — Economic events calendar

### News
- **GET /v3/newsfeed** — Financial news feed
  - Parameters: keywords (comma-separated), limit (1-500, default 500), page

### Documents (SEC Filings)
- **GET /v3/documents?code=...** — List filings/transcripts/reports for a symbol
- **GET /v3/documents/{id}?code=...** — Get document content (JSON for text, PDF binary for filings)

## Response Format: OHLCV Time Series
\`\`\`json
{
  "code": "NASDAQ:AAPL",
  "bar_end": 1733432399.0,
  "last_update": 1733432399820,
  "bar_type": "1m",
  "series": [
    { "time": 1733432340.0, "open": 242.89, "high": 243.09, "low": 242.82, "close": 243.08, "volume": 533779.0 }
  ]
}
\`\`\`

## Response Format: Quote Data
\`\`\`json
{
  "total_items": 1,
  "data": [{
    "code": "NASDAQ:AAPL",
    "status": "OPEN",
    "last_price": 239.42,
    "change_percent": -0.15,
    "change": -0.36,
    "ask": 239.47,
    "bid": 239.42,
    "volume": 47549429.0,
    "market_cap": 3558428648118.0,
    "currency_code": "USD",
    "delay_seconds": 0
  }]
}
\`\`\`

## Interactive Documentation & Examples
- API Playground: https://insightsentry.com/docs
- OpenAPI Spec: https://insightsentry.com/openapi.json
`,
  },
  {
    uri: "insightsentry://docs/workflows",
    name: "InsightSentry Integration Workflows",
    description: "Step-by-step workflows for common use cases: building trading apps, dashboards, screeners, and WebSocket integrations",
    mimeType: "text/markdown",
    content: `# InsightSentry Integration Workflows

This guide helps you build applications that integrate with the InsightSentry API. Each workflow includes the recommended tool sequence, code patterns, and best practices.

## Workflow 1: Build a Stock Dashboard

### What you need
A dashboard showing real-time quotes, charts, and company info for user-selected symbols.

### REST API Setup
\`\`\`
1. search_symbols(query="apple") → Get symbol code "NASDAQ:AAPL"
2. get_quotes(codes="NASDAQ:AAPL") → Current price, change, bid/ask
3. get_symbol_series(symbol="NASDAQ:AAPL", bar_type="day", dp=365) → 1 year daily chart
4. get_symbol_info(symbol="NASDAQ:AAPL") → Company details, sector, market cap
5. get_symbol_fundamentals(symbol="NASDAQ:AAPL") → P/E, revenue, earnings
\`\`\`

### Add Real-Time Updates via WebSocket
\`\`\`javascript
// After initial REST load, connect WebSocket for live updates
const ws = new WebSocket('wss://realtime.insightsentry.com/live');

ws.onopen = () => {
  ws.send(JSON.stringify({
    api_key: API_KEY,
    subscriptions: [
      { code: 'NASDAQ:AAPL', type: 'quote' },                    // Live price updates
      { code: 'NASDAQ:AAPL', type: 'series', bar_type: 'minute', bar_interval: 1 }  // Live chart
    ]
  }));
  // Keep-alive
  setInterval(() => ws.send('ping'), 25000);
};

ws.onmessage = (event) => {
  const msg = event.data;
  if (msg === 'pong') return;
  const data = JSON.parse(msg);
  if (data.server_time) return; // Heartbeat

  if (data.data) {
    // Quote update — data.data[0] has last_price, change, bid, ask, etc.
    updateQuoteDisplay(data.data[0]);
  } else if (data.series) {
    // Series update — data.series has new OHLCV bars
    updateChart(data.series);
  }
};
\`\`\`

### Python Equivalent
\`\`\`python
import asyncio, json, websockets, requests

API_KEY = "your-api-key"
BASE = "https://api.insightsentry.com"
HEADERS = {"Authorization": f"Bearer {API_KEY}"}

# Initial data load via REST
quote = requests.get(f"{BASE}/v3/symbols/quotes", headers=HEADERS, params={"codes": "NASDAQ:AAPL"}).json()
series = requests.get(f"{BASE}/v3/symbols/NASDAQ:AAPL/series", headers=HEADERS, params={"bar_type": "day", "dp": 365}).json()

# Then stream updates via WebSocket
async def stream():
    async with websockets.connect("wss://realtime.insightsentry.com/live") as ws:
        await ws.send(json.dumps({
            "api_key": API_KEY,
            "subscriptions": [
                {"code": "NASDAQ:AAPL", "type": "quote"},
                {"code": "NASDAQ:AAPL", "type": "series", "bar_type": "minute", "bar_interval": 1}
            ]
        }))
        async for message in ws:
            if message == "pong": continue
            data = json.loads(message)
            if "server_time" in data: continue
            process_update(data)

asyncio.run(stream())
\`\`\`

## Workflow 2: Build a Market Screener

### Step-by-step
\`\`\`
1. get_stock_screener_params() → Discover available fields, exchanges, countries
2. screen_stocks({ fields: ["close","change_percent","volume","market_cap"], sortBy: "market_cap", sortOrder: "desc", countries: ["US"] })
3. For each result, optionally: get_quotes(codes="RESULT_CODE_1,RESULT_CODE_2,...") for live prices
\`\`\`

### Implementation Pattern
\`\`\`python
# 1. Discover fields
params = requests.get(f"{BASE}/v3/screeners/stock", headers=HEADERS).json()
print("Fields:", params["available_fields"][:20])
print("Exchanges:", params["available_exchanges"])

# 2. Run screener
results = requests.post(f"{BASE}/v3/screeners/stock", headers=HEADERS, json={
    "fields": ["close", "change_percent", "volume", "market_cap"],
    "countries": ["US"],
    "exchanges": ["NASDAQ", "NYSE"],
    "sortBy": "market_cap",
    "sortOrder": "desc",
    "page": 1
}).json()

# 3. Paginate
while results["hasNext"]:
    next_page = results["current_page"] + 1
    results = requests.post(f"{BASE}/v3/screeners/stock", headers=HEADERS, json={
        "fields": ["close", "change_percent", "volume", "market_cap"],
        "countries": ["US"],
        "sortBy": "market_cap",
        "sortOrder": "desc",
        "page": next_page
    }).json()
\`\`\`

## Workflow 3: Options Trading App

### Step-by-step
\`\`\`
1. search_symbols(query="AAPL") → "NASDAQ:AAPL"
2. get_symbol_info(symbol="NASDAQ:AAPL") → Check option_info for available expirations & strikes
3. list_options(code="NASDAQ:AAPL") → All option contracts
4. get_options_expiration(code="NASDAQ:AAPL", expiration="2027-06-17", sortBy="strike_price") → Chain with Greeks
5. get_quotes(codes="OPRA:AAPL270617C200.0") → Real-time option price
6. get_symbol_series(symbol="OPRA:AAPL270617C200.0", bar_type="day") → Historical option prices
\`\`\`

### Option Code Cheatsheet
\`OPRA:AAPL260417P325.0\` = Exchange:Symbol + YYMMDD + C/P + Strike
- OPRA = Options exchange
- AAPL = Underlying
- 260417 = Expires April 17, 2026
- P = Put (C = Call)
- 325.0 = Strike price

## Workflow 4: News & Events Monitoring

### REST polling
\`\`\`
1. get_newsfeed(keywords="earnings,fed", limit=50) → Latest news
2. get_earnings(w=1, c="US") → This week's US earnings
3. get_events(w=1) → Economic events this week
\`\`\`

### Real-time news via WebSocket
\`\`\`javascript
const ws = new WebSocket('wss://realtime.insightsentry.com/newsfeed');
ws.onopen = () => {
  ws.send(JSON.stringify({ api_key: API_KEY }));
  // Server immediately sends 10 most recent news items
  // Then pushes new items as they arrive
};
ws.onmessage = (event) => {
  if (event.data === 'pong') return;
  const news = JSON.parse(event.data);
  displayNewsItem(news);
};
\`\`\`

## Workflow 5: Historical Data Pipeline (Backtesting)

### For recent data (up to 30k bars)
\`\`\`
get_symbol_series(symbol="NASDAQ:AAPL", bar_type="minute", bar_interval=5, dp=30000)
\`\`\`

### For deep history (20+ years, month by month)
\`\`\`python
# Iterate month by month
for year in range(2020, 2026):
    for month in range(1, 13):
        start_date = f"{year}-{month:02d}"
        data = requests.get(
            f"{BASE}/v3/symbols/NASDAQ:AAPL/history",
            headers=HEADERS,
            params={"bar_type": "minute", "bar_interval": 1, "start_date": start_date}
        ).json()
        save_to_database(data)
        time.sleep(1)  # Rate limit courtesy
\`\`\`

### For futures (specific contracts)
\`\`\`python
# 1. Find contracts
contracts = requests.get(f"{BASE}/v3/symbols/COMEX:GC1!/contracts", headers=HEADERS).json()

# 2. Fetch each contract's history
for contract in contracts["contracts"]:
    code = contract["code"]  # e.g., "COMEX:GCZ2024"
    for month in ["2024-09", "2024-10", "2024-11", "2024-12"]:
        data = requests.get(
            f"{BASE}/v3/symbols/{code}/history",
            headers=HEADERS,
            params={"bar_type": "minute", "bar_interval": 1, "start_date": month}
        ).json()
        time.sleep(1)
\`\`\`

## WebSocket Best Practices

### Connection Management
- Always re-send subscription message in \`onOpen\` (handles reconnection)
- Implement exponential backoff for reconnection (2s, 4s, 8s, max 30s)
- Send \`"ping"\` every 25 seconds to keep connection alive
- Set client timeout to at least 12 seconds

### Subscription Management
- Each new subscription message **replaces all** previous subscriptions
- Include ALL symbols you want in every message
- Don't send more than 300 messages per 5 minutes

### Data Handling
- Filter out \`"pong"\` string messages
- Filter out heartbeats: \`{"server_time": ...}\`
- Quote updates come in \`data\` array, series updates in \`series\` array

## Rate Limiting Tips
- REST API: Respect rate limits based on your plan tier
- Run requests sequentially for historical data (concurrent may fail)
- Screener returns up to 1000 items per page — use pagination
- get_quotes supports up to 10 symbols per call
- get_fundamentals_series supports up to 5 indicator IDs per call
`,
  },
  {
    uri: "insightsentry://docs/websocket",
    name: "InsightSentry WebSocket API Guide",
    description: "Complete WebSocket API documentation: connection, authentication, subscriptions, data formats, keepalive, error handling, and code examples",
    mimeType: "text/markdown",
    content: `# InsightSentry WebSocket API Guide

Interactive examples: https://insightsentry.com/test/realtime and https://insightsentry.com/test/newsfeed

## 1. Getting Started


### Prerequisites

          Before connecting to our WebSocket API, ensure you have the
            following:



            - API Key - Use the same API key from your InsightSentry dashboard for both REST and WebSocket APIs.

            - WebSocket Client Library - Choose one that supports automatic reconnection and retry logic

            - Connection Settings - Configure appropriate timeouts and implement ping/pong for stability




---


### Connecting to the Server

          Our WebSocket API provides two specialized endpoints for different
            types of financial data.




#### Market Data


              Real-time quotes, time series data, and tick data




#### News Feed


              Latest financial news and market updates





### Authentication

          Both endpoints require your API key for authentication. Use the same API key from your InsightSentry dashboard. The authentication format varies by endpoint.



#### Market Data Authentication

            Combine authentication with your subscription request (covered in
              the next section).





#### News Feed Authentication

            Send only your API key in this simplified format:


\`\`\`json
{
  "api_key": ""
  // No subscriptions needed for news feed

\`\`\`





#### News Feed Instant Access

            When you connect to \`/newsfeed\`, the server
              automatically sends the 10 most recent news items. This gives you
              immediate access to current news without additional requests.






## 2. Subscribing to Data Feeds


### Initial Subscription

          After connecting to the market data endpoint, send a JSON message to
            authenticate and subscribe to data feeds.

          This single message handles both authentication and your initial
            symbol subscriptions.

          **Required Message Format:**


\`\`\`json
{
  "api_key": "",
  "subscriptions": [
    // Array of subscription objects

\`\`\`


#### Subscription Parameters

          Each subscription object in the array can include these parameters:




##### Required Parameters



                - code - Symbol identifier (e.g.,  "NASDAQ:AAPL",  "BINANCE:BTCUSDT")







##### Data Type Selection



                - type - Data feed type:  "series" (default) or  "quote"



              **Tip:** Since "series" is default, you
                can omit this parameter for series data





##### Series Data Parameters (when type="series")



                - bar_type - Time interval:  "tick", "second", "minute", "hour", "day", or "week"

                - bar_interval - Number of units per bar (e.g., 1, 5, 15)

                - extended - Include extended hours (default: true) -  details below

                - dadj - Apply dividend adjustment (default: false) -  details below

                - badj - Apply back-adjustment for continuous futures contracts (default: false) -  details below

                - max_dp - Number of initial historical data points to receive on connect/reconnect (1-30,000). Default: 1. Mega plan: up to 30,000. Other plans: up to 1,000. Values exceeding your plan's limit are clamped automatically.






          **Example Subscription Message:**


\`\`\`json
{
  "api_key": "",
  "subscriptions": [
    {"code": "NASDAQ:AAPL", "type": "series", "bar_type": "minute", "bar_interval": 1, "max_dp": 100},
    {"code": "NASDAQ:TSLA", "type": "quote"}

\`\`\`


---


### Modifying Subscriptions

          You can update your subscriptions without disconnecting from the
            WebSocket.

          Send a new subscription message with your complete desired list. The
            server replaces all previous subscriptions with the new ones.



#### Complete Replacement

            Each new subscription message completely replaces your current
              subscriptions. Include all symbols you want to continue receiving
              data for.



          **Example - Updating Subscriptions:**

          To change from the previous example to track both minute bars and
            quotes for AAPL:


\`\`\`json
{
  "api_key": "",
  "subscriptions": [
    {"code": "NASDAQ:AAPL", "type": "series", "bar_type": "minute", "bar_interval": 1, "max_dp": 100},
    {"code": "NASDAQ:AAPL", "type": "quote"}
    // NASDAQ:TSLA quote subscription is removed as it's not in the new list

\`\`\`


---


### Subscription Rules & Limits

          Follow these important guidelines when managing your subscriptions:




#### Required Authentication

              Every subscription message must include your valid
                \`api_key\`.





#### Rate Limiting

              Don't send **300 messages per 5 minutes**. If
                you exceed this limit, your messages will be ignored
                temporarily.

              **Note:** This only affects new messages you send.
                Your existing data feed continues uninterrupted. Data you
                receive has no rate limit or any restriction.





#### Empty Subscriptions

              You cannot send an empty \`subscriptions\` array. To
                stop all data, disconnect the WebSocket and reconnect when
                needed.





#### Multiple Symbols

              Subscribe to multiple symbols in one message by adding multiple
                objects to the \`subscriptions\` array (subject to your
                plan limits).







## 3. Response Data Formats

          The server sends real-time data updates as JSON messages. The format

          For complete field descriptions, see the corresponding REST API
            documentation: \`/symbols/:symbol/series\` or
            \`/symbols/quotes\`.


### Series Data (type: "series")

          Series data provides OHLCV (Open, High, Low, Close, Volume) bar
            information and tick data.






#### Real-time Updates


                  Regardless of your chosen \`bar_type\` and
                    \`bar_interval\`, you receive updates whenever the
                    close price or volume changes within the current bar period.

                  **Example:** With
                    \`bar_type: "hour"\`, you get real-time
                    updates throughout the hour, not just once per hour.











#### Update Frequency by Bar Type

                Data delivery varies based on your \`bar_type\`
                  subscription:



                    **Tick Data** (
                    \`bar_type: "tick"\`) - Data pushed for
                    every individual trade


                    **Second Intervals** (
                    \`bar_type: "second"\`) - Data pushed
                    only when close price or volume changes


                    **Higher Timeframes** (
                    \`bar_type: "minute"\` or above) - Data
                    pushed when price/volume changes AND when new bar periods
                    start







\`\`\`json
{
        "code": "NASDAQ:AAPL",
        "bar_end": 1733432399.0,
        "last_update": 1733432399820,
        "bar_type": "1m",
        "series": [
          {
            "time": 1733432340.0,
            "open": 242.89,
            "high": 243.09,
            "low": 242.82,
            "close": 243.08,
            "volume": 533779.0

\`\`\`


---


### Quote Data (type: "quote")

          Quote data provides real-time market information including current
            prices, trading volume, and bid/ask spreads.

          This data type is ideal for monitoring current market conditions and
            building trading interfaces.


\`\`\`json
{
        "last_update": 1757061265540,
        "total_items": 1,
        "data": [
          {
            "code": "NASDAQ:AAPL",
            "status": "PRE",
            "lp_time": 1757061117.0,
            "volume": 47549429.0,
            "last_price": 239.42,
            "change_percent": -0.15,
            "change": -0.36,
            "ask": 239.47,
            "bid": 239.42,
            "ask_size": 2.0,
            "bid_size": 1.0,
            "prev_close_price": 238.47,
            "open_price": 238.45,
            "low_price": 236.74,
            "high_price": 239.8999,
            "market_cap": 3558428648118.0,
            "currency_code": "USD",
            "delay_seconds": 0

\`\`\`






#### Understanding delay_seconds


                  The \`delay_seconds\` field indicates the data
                    delay in seconds:



                    - 0 - Real-time with no artificial delay

                    - 900 - Data is delayed by 900 seconds

                    - -1 - End-of-day (EOD)











## 4. Additional Parameters

          The WebSocket API supports several additional parameters for
            fine-tuning your data feeds and customizing the response format.


### Extended Market Hours (extended)

          The \`extended\` parameter applies to many US and Global
            stock markets.



            - extended: true (default) - Includes pre-market and after-hours trading data where available. For US equities, this covers 4:00 AM - 9:30 AM ET (pre-market) and 4:00 PM - 8:00 PM ET (after-hours).

            - extended: false - Only includes regular trading hours data.

            - Note: Not all markets support extended hours trading. Setting extended: true for markets without extended hours will return only regular session data.



          **Example:**


\`\`\`json
{
  "api_key": "",
  "subscriptions": [
    {"code": "NASDAQ:AAPL", "bar_type": "minute", "bar_interval": 1, "extended": false}

\`\`\`


---


### Dividend Adjustment (dadj)

          For equities data, you can request dividend-adjusted price series.



            - dadj: true - Applies dividend adjustments to all price values.

            - dadj: false (default) - Shows unadjusted prices.



          **Example:**


\`\`\`json
{
  "api_key": "",
  "subscriptions": [
    {"code": "NASDAQ:AAPL", "bar_type": "day", "bar_interval": 1, "dadj": true}

\`\`\`


---


### Back-Adjustment (badj)

          For continuous futures contracts (e.g., ES1!, NQ1!), you can request
            back-adjusted price series to remove price gaps between contract rollovers.



            - badj: true - Applies back-adjustment to smooth price gaps at contract rollovers.

            - badj: false (default) - Shows unadjusted prices with natural contract rollover gaps.



          **Example:**


\`\`\`json
{
  "api_key": "",
  "subscriptions": [
    {"code": "CME_MINI:ES1!", "bar_type": "day", "bar_interval": 1, "badj": true}

\`\`\`


---


### Settlement Price (settlement)

          For futures and other applicable instruments, you can control
            whether historical data uses settlement prices for the close value.



            - settlement: true - Uses settlement prices as the close price where applicable.

            - settlement: false (default) - Uses the regular close price (last traded price).



          **Example:**


\`\`\`json
{
  "api_key": "",
  "subscriptions": [
    {"code": "CME_MINI:ES1!", "bar_type": "day", "bar_interval": 1, "settlement": false}

\`\`\`


### Initial Data Points (max_dp)

          Control how many historical data points you receive when first
            connecting or reconnecting to a symbol. Accepts a number from 1 to 30,000.
            If not specified, defaults to **1** (only the current bar).

          When you connect (or reconnect), the first message will contain the
            most recent \`max_dp\` bars in the \`series\` property, followed
            by real-time updates with single bars.



            - Mega Plan (10+ symbol subscriptions): up to 30,000 data points.

            - Other Plans: up to 1,000 data points.

            - If you specify a value higher than your plan allows, it will be automatically clamped to your plan's maximum.



          **Example:**


\`\`\`json
{
  "api_key": "",
  "subscriptions": [
    {"code": "NASDAQ:AAPL", "bar_type": "minute", "bar_interval": 1, "max_dp": 5000}

\`\`\`





## 5. Maintaining Connection & Best Practices


### Automatic Re-subscription






#### Critical Implementation Detail

                Configure your WebSocket client to automatically send your
                  subscription message in the \`onOpen\` event handler.
                  This ensures immediate re-subscription after any disconnection
                  (network issues, server restarts).





---


### Server Heartbeat (Keep-Alive)

          Our server automatically sends periodic timestamp messages
            (approximately every 10 seconds) to maintain connection health and
            allow connectivity verification.

          **Heartbeat Message Format:**


\`\`\`json
{"server_time": 1741397070281}
\`\`\`


---


### Preventing Connection Drops

          Some WebSocket libraries drop connections during inactivity periods.
            Implement a ping-pong mechanism for connection stability.



#### Ping-Pong Implementation



              - Send a 'ping' text message every 20-30 seconds

              - Server responds with 'pong' to confirm connection

              - Filter out 'pong' messages in your data handler







#### Rate Limiting Warning

            Don't send pings more than once every 15 seconds to avoid
              triggering rate limits. This WebSocket rate limit is separate from
              REST API limits.



\`\`\`python
import asyncio
import websockets
import json

async def websocket_client():
    uri = 'wss://realtime.insightsentry.com/live'

    async with websockets.connect(uri) as websocket:
        # Start ping task
        ping_task = asyncio.create_task(send_ping(websocket))

            async for message in websocket:

                    print('Received pong from server')
                    continue
                # Handle other messages here

        except websockets.exceptions.ConnectionClosed:
            print('WebSocket connection closed')
        finally:
            ping_task.cancel()

async def send_ping(websocket):
    while True:

            await asyncio.sleep(20)
            await websocket.send('ping')
        except asyncio.CancelledError:
            break

# Run the client
asyncio.run(websocket_client())
\`\`\`


---


### Client-Side Timeout

          Configure your WebSocket library with an appropriate timeout value.
            We recommend a minimum timeout of **12 seconds**. This
            helps handle periods of low market activity (e.g., weekends,
            holidays) where price updates might be infrequent, preventing
            premature disconnection by the client.





## 6. Error Handling

          If you send an invalid request (e.g., incorrect format, invalid
            symbol) or if a server-side error occurs related to your request,
            the server will send a JSON-encoded error message:


\`\`\`json
{
  "message": "Invalid Symbol Code"

\`\`\`



            - The WebSocket connection typically remains open after an error message is sent.

            - However, processing for the invalid request will stop.

            - Action Required: You should close the connection, correct the subscription request that caused the error, and then establish a new connection.

            - Always validate symbol codes and message formats before sending subscription requests.












## 7. Code Examples

          The following examples demonstrate how to connect to our WebSocket
            API and handle real-time data feeds using popular programming
            languages.






#### Before You Start

                Replace \`\` placeholders with your actual
                  API key in all examples.










## FAQ



### Q: WebSocket is disconnected frequently

            There could be several causes. First, check if your main thread is
              blocked due to heavy data processing. If the main thread is
              blocked, the WebSocket library's internal ping mechanism may
              fail to respond, which can lead to disconnection. This is one of
              the most common causes. You can easily identify this by comparing
              your machine's current time with the \`server_time\`
              field in the messages sent from our servers. If
              \`Time.inMilliseconds - server_time\` results in a
              negative value, it indicates that your main thread is being
              blocked.




### Q: There are missing messages when using 'second' as
              bar_type and 1 as bar_interval

            For the 1-second time frame, a bar message is sent only when there
              is a change in the close price or volume. This means you may not
              receive a message every second. To handle missing bars, you can
              normalize your data by filling in with the previous bar's
              values when no update is received.`,
  },
  {
    uri: "insightsentry://docs/screener",
    name: "InsightSentry Screener API Guide",
    description: "Screener API: discover available fields, filter stocks/ETFs/bonds/crypto with custom criteria",
    mimeType: "text/markdown",
    content: `# InsightSentry Screener API Guide

Full documentation: https://insightsentry.com/docs

## 1. Overview

          The Screener API allows you to filter and retrieve financial
            instruments across multiple asset classes including stocks, ETFs,
            bonds, and cryptocurrencies. You can query data with custom field
            selections, apply filters by exchange or country, and sort results.


### Supported Asset Types



              stock

              Equities



              etf

              Exchange-Traded Funds



              bond

              Fixed Income



              crypto

              Cryptocurrencies





### Base URL


\`\`\`bash
https://api.insightsentry.com/v3/screeners/{type}
\`\`\`





## 2. Available Options

          Before querying the screener, you can discover available fields,
            exchanges, and countries for each asset type using a GET request.


### Endpoint


\`\`\`bash
GET https://api.insightsentry.com/v3/screeners/{type}
\`\`\`


### Example Request


\`\`\`bash
GET https://api.insightsentry.com/v3/screeners/stock
\`\`\`


### Response


\`\`\`json
{
  "available_fields": [
    "close",
    "change",
    "high",
    "low",
    "open",
    "volume",
    "market_cap",
    "..."
  ],
  "available_exchanges": [
    "NASDAQ",
    "NYSE",
    "AMEX",
    "..."
  ],
  "available_countries": [
    "US",
    "CA",
    "GB",
    "..."
  ],
  "sortOrder": ["asc", "desc"]

\`\`\`






#### Asset Type Differences


                  **Crypto**: Does not support country filtering

                  **Bond**: Has different country codes specific
                    to bond markets

                  Each asset type has its own set of available fields tailored
                    to that market









## 3. Query Screener

          Use a POST request to query the screener with your desired fields,
            filters, and sorting options.


### Endpoint


\`\`\`bash
POST https://api.insightsentry.com/v3/screeners/{type}
\`\`\`


### Request Body



| Parameter      | Type     | Required | Description                                                                                                    |
| -------------- | -------- | -------- | -------------------------------------------------------------------------------------------------------------- |
| fields         | string[] | Yes      | Array of fields to retrieve (1-10 fields)                                                                      |
| page           | number   | No       | Page number for pagination (default: 1)                                                                        |
| sortBy         | string   | No       | Field to sort by, must be one of the requested fields or
                    "name" (default: "name")          |
| sortOrder      | string   | No       | "asc" or "desc" (default:
                    "asc")                                                           |
| exchanges      | string[] | No       | Filter by specific exchanges                                                                                   |
| countries      | string[] | No       | Filter by country codes (not available for crypto)                                                             |
| ignore_invalid | boolean  | No       | If true, invalid fields/exchanges/countries are filtered out
                    instead of returning an error |




### Example Request


\`\`\`json
POST https://api.insightsentry.com/v3/screeners/stock

{
  "fields": ["close", "change_percent", "volume", "market_cap"],
  "page": 1,
  "sortBy": "market_cap",
  "sortOrder": "desc",
  "exchanges": ["NASDAQ", "NYSE"],
  "countries": ["US"]

\`\`\`






#### Field Validation



                  - At least one field is required

                  - Maximum of 10 fields per request

                  - Up to 1000 items are returned per request

                  - Field names are case-insensitive and will be normalized to lowercase

                  - The sortBy field must be one of the requested fields or "name"










## 4. Response Format

          The screener returns paginated results with metadata about the
            current page and total available data.


### Response Structure


\`\`\`json
{
  "hasNext": true,
  "current_page": 1,
  "total_page": 15,
  "current_items": 1000,
  "data": [
    {
      "symbol_code": "NASDAQ:AAPL",
      "name": "Apple Inc.",
      "close": 195.89,
      "change_percent": 1.25,
      "volume": 52436789,
      "market_cap": 3050000000000,
      "country": "US",
      "currency": "USD",
      "delay_seconds": 0,
      "fundamental_currency": "USD"

\`\`\`


### Response Fields



#### Pagination Metadata:



              - hasNext: Boolean indicating if more pages are available

              - current_page: Current page number

              - total_page: Total number of pages

              - current_items: Number of items in current response







#### Common Fields in Data:



              - symbol_code: Unique identifier (EXCHANGE:SYMBOL format)

              - name: Description/name of the instrument

              - country: Country code (not for crypto)

              - currency: Trading currency

              - delay_seconds: Data delay in seconds (0 = real-time)

              - fundamental_currency: Currency for fundamental data










## 5. Examples


### Stock Screener

          Find US stocks by market cap with price data:


\`\`\`json
POST https://api.insightsentry.com/v3/screeners/stock

{
  "fields": ["close", "change", "volume", "market_cap"],
  "page": 1,
  "sortBy": "market_cap",
  "sortOrder": "desc",
  "countries": ["US"]

\`\`\`


### ETF Screener

          Query ETFs from specific exchanges:


\`\`\`json
POST https://api.insightsentry.com/v3/screeners/etf

{
  "fields": ["close", "volume", "change"],
  "exchanges": ["NYSE", "NASDAQ"],
  "sortBy": "volume",
  "sortOrder": "desc"

\`\`\`


### Crypto Screener

          Screen cryptocurrencies by volume:


\`\`\`json
POST https://api.insightsentry.com/v3/screeners/crypto

{
  "fields": ["close", "volume", "change"],
  "sortBy": "volume",
  "sortOrder": "desc"

\`\`\`


### Bond Screener

          Query bonds from specific countries:


\`\`\`json
POST https://api.insightsentry.com/v3/screeners/bond

{
  "fields": ["close", "yield"],
  "countries": ["US", "GB"],
  "sortBy": "yield",
  "sortOrder": "desc"

\`\`\`


### With ignore_invalid Flag

          Use \`ignore_invalid\` when you want to attempt queries
            with fields that might not exist:


\`\`\`json
POST https://api.insightsentry.com/v3/screeners/stock

{
  "fields": ["close", "volume", "some_unknown_field"],
  "ignore_invalid": true

\`\`\`

          With \`ignore_invalid: true\`, the API will filter out
            "some_unknown_field" and return results with only the
            valid fields.`,
  },
  {
    uri: "insightsentry://docs/options",
    name: "InsightSentry Options API Guide",
    description: "Options API: list options, option chains, Greeks, option code format, historical data",
    mimeType: "text/markdown",
    content: `# InsightSentry Options API Guide

Full documentation: https://insightsentry.com/docs

## 1. Symbol Search


### Finding Symbols

          Before working with options data, you need to identify the correct
            symbol codes for the underlying assets.

          The symbol search endpoint helps you discover available symbols and
            their exact format required for options queries.


### Search Endpoint

          Use the \`/v3/symbols/search\` endpoint to find symbols:


\`\`\`bash
GET https://api.insightsentry.com/v3/symbols/search?query=apple
\`\`\`





## 2. Get Available Options


### Options List Endpoint

          Once you have the underlying symbol, retrieve all available option
            contracts using the \`/v3/options/list\` endpoint.

          This endpoint returns all available options for the specified
            underlying symbol, including different expirations and strike
            prices, excluding expired options.


### Example


\`\`\`bash
GET https://api.insightsentry.com/v3/options/list?code=NASDAQ:AAPL
\`\`\`

          Response includes all available option contracts:


\`\`\`json
{
            "last_update": 1756912027000,
            "codes": [
              "OPRA:AAPL260417P325.0",
              "OPRA:AAPL260618C5.0"

\`\`\`


#### Optional Filters

          You can filter the options list by expiration date range, option type,
            and/or strike price range:

\`\`\`bash
# Filter by expiration date range
GET /v3/options/list?code=NASDAQ:AAPL&expiration_min=2026-06-01&expiration_max=2026-12-31

# Filter by option type (call or put)
GET /v3/options/list?code=NASDAQ:AAPL&type=call

# Filter by strike price range (±10% of current underlying price)
GET /v3/options/list?code=NASDAQ:AAPL&range=10

# Combine filters
GET /v3/options/list?code=NASDAQ:AAPL&type=put&expiration_min=2026-06-01&range=5
\`\`\`

          - **expiration_min**: Only return options expiring on or after this date (YYYY-MM-DD)
          - **expiration_max**: Only return options expiring on or before this date (YYYY-MM-DD)
          - **type**: Filter by option type: \`call\` or \`put\`
          - **range**: Strike price range as a percentage of the current underlying price. For example, range=10 returns only options with strikes within ±10% of the current price. Must be an integer >= 1. 





#### Futures Options

                For futures options, you must use specific contract codes
                  rather than continuous contracts:



                  - Use: CME_MINI:NQU2025 (specific contract)

                  - Not: CME_MINI:NQ1! (continuous contract)

                  - Each futures contract has its own set of options

                  - Options expire before the underlying futures contract










## 3. Get Option Chain Info


### Symbol Metadata

          Before making requests to the expiration or strike filter endpoints,
            you need to discover what option data is available for a symbol.

          The \`/v3/symbols/:symbol/info\` endpoint provides
            comprehensive metadata about a symbol, including the
            \`option_info\` field which contains available expiration
            dates and strike prices for all option series.


### Endpoint

          Get symbol information including option chain metadata:


\`\`\`bash
GET https://api.insightsentry.com/v3/symbols/CME_MINI:NQZ2025/info
\`\`\`


### Response Structure

          The response includes basic symbol information and option chain data:


\`\`\`json
{
  "code": "CME_MINI:NQZ2025",
  "type": "FUTURES",
  "description": "E-mini Nasdaq-100 Futures (Dec 2025)",
  "currency_code": "USD",
  "expiration": 20251219,
  "option_info": [
    {
      "name": "E-mini Nasdaq-100 Options",
      "type": "AMERICAN",
      "series": [
        {
          "expiration_date": 20251219,
          "underlying": "CME_MINI:NQZ2025",
          "strikes": [2500.0, 3000.0, 3500.0, "...", 35500.0]

    },
    {
      "name": "E-mini Nasdaq-100 Monday Weekly Options - Week 2",
      "type": "EUROPEAN",
      "series": [
        {
          "expiration_date": 20251013,
          "underlying": "CME_MINI:NQZ2025",
          "strikes": [17500.0, 18000.0, "...", 29000.0]

\`\`\`



#### Option Info Structure:



              - name: Option series name (e.g., "E-mini Nasdaq-100 Options")

              - type: Exercise style ("AMERICAN" or "EUROPEAN")

              - series: Array of option series containing: expiration_date: YYYYMMDD format (e.g., 20251219)

                  - underlying: The underlying contract code

                  - strikes: Array of available strike prices













#### Using Option Info Data


                  Extract expiration dates from
                    \`option_info.series[].expiration_date\`
                    and use with the
                    \`/options/expiration\`
                    endpoint.

                  Extract strike prices from
                    \`option_info.series[].strikes\`
                    and use with the
                    \`/options/strike\`
                    endpoint.

                  Some symbols have multiple option series (weekly, monthly,
                    EOM) - each with different expiration dates and strike
                    ranges.











#### Important Notes



                  - Not all symbols have options data (check if  option_info field exists)

                  - For futures options, you must use the specific futures contract code (e.g., CME_MINI:NQZ2025), not continuous contracts (e.g., CME_MINI:NQ1!)

                  - The strikes array can contain hundreds of values - the example shows truncated data

                  - Equity options typically have more standardized expiration dates and strikes








### Practical Workflow

          Here's how to use the symbol info endpoint to discover and filter
            option data:



#### Example 1: Filter by Expiration Date


              1. Get symbol info:

                  GET /v3/symbols/CME_MINI:NQZ2025/info

              2. Extract an expiration date from response (e.g., 20251013)

              3. Use with expiration endpoint:

                  GET
                  /v3/options/expiration?code=CME_MINI:NQZ2025&expiration=2025-10-13






#### Example 2: Filter by Strike


              1. Get symbol info:

                  GET /v3/symbols/CME_MINI:NQZ2025/info

              2. Extract a strike price from response (e.g., 25000.0)

              3. Use with strike endpoint:

                  GET /v3/options/strike?code=CME_MINI:NQZ2025&strike=25000







## 4. Understanding Option Codes


### Option Code Structure

          Option codes contain embedded information about the option type,
            expiration date, and strike price.

          Understanding this structure helps you interpret and construct
            option codes programmatically.


### Code Format Breakdown



| Exchange  | Symbol | Expiration | Type | Strike |
| --------- | ------ | ---------- | ---- | ------ |
| OPRA:     | AAPL   | 260417     | P    | 325.0  |
| CME_MINI: | NQ     | 250919     | P    | 24450  |




### Format Examples




#### Equity Option (AAPL Put):

              OPRA:AAPL260417P325.0



                - OPRA: Options exchange

                - AAPL: Apple Inc. stock

                - 260417: Expires April 17, 2026 (YYMMDD)

                - P: Put option

                - 325.0: Strike price $325.00







#### Futures Option (NASDAQ Mini Put):

              CME_MINI:NQ250919P24450



                - CME_MINI: CME futures exchange

                - NQ: NASDAQ 100 E-mini futures

                - 250919: Expires September 19, 2025 (YYMMDD)

                - P: Put option

                - 24450: Strike price 24,450 index points











#### Option Type Codes


                  **C** = Call option (right to buy)

                  **P** = Put option (right to sell)









## 5. Option Chains


### Filtering Option Data

          Option chains allow you to filter available options by specific
            criteria such as expiration date or strike price.

          These endpoints are useful when you need to focus on options with
            specific characteristics rather than retrieving all available
            contracts.


### Filter by Expiration Date

          Use the \`/v3/options/expiration\` endpoint to get options
            by expiration. Provide either an exact date or a date range:


\`\`\`bash
# Exact expiration date
GET /v3/options/expiration?code=NASDAQ:AAPL&expiration=2027-06-17

# Expiration date range
GET /v3/options/expiration?code=NASDAQ:AAPL&from=2026-06-01&to=2026-12-31

# Only from (all expirations after this date)
GET /v3/options/expiration?code=NASDAQ:AAPL&from=2027-01-01

# Only to (all expirations before this date)
GET /v3/options/expiration?code=NASDAQ:AAPL&to=2026-06-30
\`\`\`

          - **expiration**: Exact date match (ignored when from/to is provided)
          - **from**: Minimum expiration date (inclusive)
          - **to**: Maximum expiration date (inclusive)
          - At least one of expiration, from, or to must be provided.


#### Strike Range Filter

          Use the \`range\` parameter to limit results to strikes within a
            percentage of the current underlying price:

\`\`\`bash
# Only strikes within ±10% of current AAPL price
GET /v3/options/expiration?code=NASDAQ:AAPL&expiration=2027-06-17&range=10
\`\`\`

          Must be an integer >= 1. 

#### Sorting Options

          You can sort the results using \`sortBy\` and
            \`sort\` parameters:


\`\`\`bash
GET https://api.insightsentry.com/v3/options/expiration?code=NASDAQ:AAPL&expiration=2027-06-17&sortBy=strike_price&sort=asc
\`\`\`



##### Available Sort Fields (sortBy):


              type
              ask_price
              bid_price
              delta
              gamma
              expiration
              implied_volatility
              rho
              strike_price
              theoretical_price
              theta
              vega

            **sort:** Use \`asc\` (ascending) or
              \`desc\` (descending). Default is \`asc\`.



          Returns option chain data for the specified expiration date:


\`\`\`json
{
  "underlying_code": "NASDAQ:AAPL",
  "last_update": 1756912027000,
  "data": [
    {
      "code": "OPRA:AAPL270617C150.0",
      "ask_price": 12.5,
      "bid_price": 12.0,
      "delta": 0.65,
      "gamma": 0.02,
      "implied_volatility": 0.25,
      "type": "CALL",
      "rho": 0.08,
      "strike_price": 150,
      "theoretical_price": 12.25,
      "theta": -0.05,
      "vega": 0.15,
      "bid_iv": 0.24,
      "ask_iv": 0.26,
      "expiration": 20270617
    },
    {
      "code": "OPRA:AAPL270617P150.0",
      "ask_price": 8.2,
      "bid_price": 7.8,
      "delta": -0.35,
      "gamma": 0.02,
      "implied_volatility": 0.23,
      "type": "PUT",
      "rho": -0.06,
      "strike_price": 150,
      "theoretical_price": 8.0,
      "theta": -0.04,
      "vega": 0.15,
      "bid_iv": 0.22,
      "ask_iv": 0.24,
      "expiration": 20270617

\`\`\`


### Filter by Strike Price

          Use the \`/v3/options/strike\` endpoint to get options at a
            specific strike price:


\`\`\`bash
GET https://api.insightsentry.com/v3/options/strike?code=NASDAQ:AAPL&strike=210
\`\`\`

          You can also sort by any of the available fields (same as expiration
            endpoint):


\`\`\`bash
GET https://api.insightsentry.com/v3/options/strike?code=NASDAQ:AAPL&strike=210&sortBy=expiration&sort=asc
\`\`\`

          Returns option chain data for the specified strike price:


\`\`\`json
{
  "underlying_code": "NASDAQ:AAPL",
  "last_update": 1756912027000,
  "data": [
    {
      "code": "OPRA:AAPL270617C210.0",
      "ask_price": 8.5,
      "bid_price": 8.0,
      "delta": 0.45,
      "gamma": 0.018,
      "implied_volatility": 0.28,
      "type": "CALL",
      "rho": 0.06,
      "strike_price": 210,
      "theoretical_price": 8.25,
      "theta": -0.08,
      "vega": 0.18,
      "bid_iv": 0.27,
      "ask_iv": 0.29,
      "expiration": 20270617
    },
    {
      "code": "OPRA:AAPL280115C210.0",
      "ask_price": 15.2,
      "bid_price": 14.8,
      "delta": 0.52,
      "gamma": 0.015,
      "implied_volatility": 0.26,
      "type": "CALL",
      "rho": 0.09,
      "strike_price": 210,
      "theoretical_price": 15.0,
      "theta": -0.06,
      "vega": 0.22,
      "bid_iv": 0.25,
      "ask_iv": 0.27,
      "expiration": 20280115

\`\`\`






#### Option Chain Data Fields




                      Pricing:



                        - ask_price ,  bid_price

                        - theoretical_price - Fair value estimate

                        - bid_iv ,  ask_iv - Implied volatility at bid/ask





                      Greeks:



                        - delta - Price sensitivity to underlying

                        - gamma - Delta change rate

                        - theta - Time decay

                        - vega

                        - rho






                    \`expiration\`
                      : Date in YYYYMMDD format (e.g., 20270617)

                    \`type\`
                      : "CALL" or "PUT"









#### When to Use Each Endpoint




##### Expiration Filter

                Perfect for analyzing options expiring on earnings
                  announcements or other specific events. Sort by strike_price
                  to see the full options chain for a specific expiration.




##### Strike Filter

                Ideal for comparing options at the same strike across
                  different expiration dates. Sort by expiration to see time
                  decay effects.








## 6. Real-time Quotes


### Getting Real-time Option Prices

          Once you have option codes, retrieve real-time pricing and volume
            data using the \`/v3/symbols/quotes\` endpoint.

          This endpoint provides current bid/ask prices, last trade
            information, and trading volume for option contracts.


### Multiple Option Quotes

          Request quotes for multiple options (up to 10) by separating codes
            with commas:


\`\`\`bash
GET https://api.insightsentry.com/v3/symbols/quotes?codes=OPRA:AAPL271217P370.0,OPRA:AAPL251219C145.0,OPRA:AAPL261218P50.0
\`\`\`

          Response includes real-time data for each option:


\`\`\`json
{
        "last_update": 1756978199901,
        "_ct": 1756978199796,
        "total_items": 3,
        "data": [
        {
          "code": "OPRA:AAPL271217P370.0",
          "status": "CLOSED",
          "lp_time": 1750065411.0,
          "volume": 0.0,
          "last_price": 166.14,
          "ask": 133.55,
          "bid": 129.75,
          "ask_size": 107.0,
          "bid_size": 107.0,
          "open_price": 166.14,
          "low_price": 166.14,
          "high_price": 166.14,
          "delay_seconds": 0
        },
        {
          "code": "OPRA:AAPL251219C145.0",
          "status": "CLOSED",
          "lp_time": 1756918904.0,
          "volume": 6.0,
          "last_price": 94.2,
          "change_percent": 10.02,
          "change": 8.6,
          "ask": 96.15,
          "bid": 94.4,
          "ask_size": 195.0,
          "bid_size": 258.0,
          "prev_close_price": 85.62,
          "open_price": 93.1,
          "low_price": 93.1,
          "high_price": 94.28,
          "delay_seconds": 0
        },
        {
          "code": "OPRA:AAPL261218P50.0",
          "status": "CLOSED",
          "lp_time": 1756910857.0,
          "volume": 1.0,
          "last_price": 0.09,
          "change_percent": -18.18,
          "change": -0.02,
          "ask": 0.12,
          "bid": 0.07,
          "ask_size": 111.0,
          "bid_size": 98.0,
          "prev_close_price": 0.11,
          "open_price": 0.09,
          "low_price": 0.09,
          "high_price": 0.09,
          "delay_seconds": 0

\`\`\`


### Request Limits



#### Multiple Symbol Guidelines:



              - Maximum 10 symbols per request

              - Separate codes with commas (no spaces)

              - All codes must be valid symbols (options, stocks, futures, etc.)

              - Mixed asset types are supported








## 7. Historical Option Data


### Historical OHLCV Data

          Retrieve historical price (up to 30k data points) and volume data
            for option contracts using the
            \`/v3/symbols/:symbol/series\` endpoint.

          This endpoint provides OHLCV (Open, High, Low, Close, Volume) data
            for analyzing option price movements over time.






#### Important Limitations

                Historical options data has the following restrictions:



                  - Expired options are NOT supported

                  - Futures options are NOT supported

                  - Only equity options are currently available

                  - Options must still be active and trading








### Historical Data Request

          Get daily historical data for an option contract:


\`\`\`bash
GET https://api.insightsentry.com/v3/symbols/OPRA:AAPL271217P205.0/series?bar_type=day&bar_interval=1&dp=20000
\`\`\`

          You can also request different time intervals:


\`\`\`bash
# Hourly data
GET https://api.insightsentry.com/v3/symbols/OPRA:AAPL271217P205.0/series?bar_type=hour&bar_interval=1&dp=20000

# 5-minute data
GET https://api.insightsentry.com/v3/symbols/OPRA:AAPL271217P205.0/series?bar_type=minute&bar_interval=5&dp=20000
\`\`\`

          Response provides OHLCV data with timestamps:


\`\`\`json
{
  "code": "OPRA:AAPL271217P205.0",
  "bar_end": 1733432340.0,
  "last_update": 1733432400000,
  "_ct": 1733432401234,
  "bar_type": "1D",
  "series": [
    {
      "time": 1704153600.0,
      "open": 82.50,
      "high": 84.75,
      "low": 81.25,
      "close": 83.80,
      "volume": 1450
    },
    {
      "time": 1704240000.0,
      "open": 84.00,
      "high": 86.25,
      "low": 83.50,
      "close": 85.90,
      "volume": 2100
    },
    {
      "time": 1704326400.0,
      "open": 85.75,
      "high": 87.20,
      "low": 84.90,
      "close": 86.45,
      "volume": 1890

\`\`\`


### Request Parameters



#### Available Parameters:



              - code (required): Option code from /v3/options/list endpoint

              - bar_type (optional): tick, second, minute, hour, day, week, month (default: day)

              - bar_interval (optional): Number of bars (default: 1)

              - extended (optional): Include extended hours data (default: true)

              - dadj (optional): Dividend adjustment for equities (default: false)

              - badj (optional): Back-adjustment for continuous futures (default: true)







## Try the API Playground


### Interactive REST API Demo

            You can experiment with all our endpoints using the interactive

                API playground

              .






#### How to Use



                    - Choose an endpoint and fill in parameters

                    - Submit requests and view responses

                    - Copy cURL and convert it to your code using AI or other tools`,
  },
  {
    uri: "insightsentry://docs/history",
    name: "InsightSentry History Endpoints Guide",
    description: "Intraday historical data endpoints (second/minute/hour): query parameters, concurrency limits, caching, and when to use history vs series",
    mimeType: "text/markdown",
    content: `# History Endpoints Guide

Full documentation: https://insightsentry.com/docs/archive

## Endpoints

\`\`\`
GET /v3/symbols/{code}/history
\`\`\`

## Supported Bar Types

Only intraday intervals are supported:

| bar_type | start_date format | Example |
|----------|-------------------|---------|
| second   | YYYY-MM-DD        | 2024-06-14 |
| minute   | YYYY-MM           | 2024-06 |
| hour     | YYYY-MM           | 2024-06 |

**Not supported:** tick, day, week, month. For day/week/month, use \`/series\` — it already returns all available data points.

## Query Parameters

| Parameter | Required | Default | Description |
|-----------|----------|---------|-------------|
| bar_type | Yes | — | \`second\`, \`minute\`, or \`hour\` |
| start_date | Yes | — | Period to fetch. \`YYYY-MM-DD\` for second, \`YYYY-MM\` for minute/hour. Cannot be in the future. \`start_ym\` is accepted as an alias. |
| bar_interval | No | 1 | Interval within the bar type. second: 1,5,10,15,30,45. minute: 1–1440. hour: 1–24. |
| extended | No | true | Include pre/post market hours. |
| badj | No | true | Back-adjusted prices (futures). |
| dadj | No | false | Dividend-adjusted prices (equities). |
| settlement | No | false | Settlement prices (futures). |

## Concurrency & Queuing

- Each user can run up to **4 concurrent history requests**.
- If at the limit, the request waits in a queue for up to **40 seconds** for a slot to free up.
- If no slot opens: **429 Too Many Requests**.
- If the handling instance is temporarily at capacity: **503 Service Unavailable**. Retrying the request may route it to a different instance.
- Recommendation: process requests in batches of 4, wait for each batch to complete.

## Caching

- Completed historical periods (past months/dates) are cached for a longer duration via CDN.
- Current period data is cached for less than a day.
- For real-time or recent data, use \`/series\` endpoints instead.

## When to Use History vs Series

Use **history** when:
- You need second/minute/hour data from a specific past month or date
- You're building a dataset spanning multiple months of intraday data
- \`/series\` doesn't return enough data points (its max is 30k bars)

Use **series** when:
- You need recent or real-time data
- You're working with day/week/month bar types (all data is returned by /series)
- You need low-latency responses without queuing

## Response

On success (200), returns OHLCV JSON with a \`series\` array. For second-level requests on a non-trading day, the response is still 200 but contains a message instead of data.

## Example Requests

\`\`\`
# 1-minute bars for June 2024
GET /v3/symbols/NASDAQ:AAPL/history?bar_type=minute&bar_interval=1&start_date=2024-06

# 1-second bars for a specific trading day
GET /v3/symbols/NASDAQ:AAPL/history?bar_type=second&bar_interval=1&start_date=2024-06-14

# Hourly bars for March 2024
GET /v3/symbols/CME_MINI:NQ1!/history?bar_type=hour&bar_interval=1&start_date=2024-03
\`\`\`

## Batch Fetching (Python)

\`\`\`python
import requests

API_KEY = "your_api_key"
BASE = "https://api.insightsentry.com/v3/symbols"
HEADERS = {"Authorization": f"Bearer {API_KEY}"}

symbol = "NASDAQ:AAPL"
months = ["2024-01", "2024-02", "2024-03", "2024-04",
          "2024-05", "2024-06", "2024-07", "2024-08"]

# Batch by 4 to stay within concurrency limit
for i in range(0, len(months), 4):
    batch = months[i:i+4]
    # Use asyncio/threading for parallel requests within batch
    for month in batch:
        r = requests.get(f"{BASE}/{symbol}/history",
                         headers=HEADERS,
                         params={"bar_type": "minute", "start_date": month})
        if r.status_code == 200:
            print(f"{month}: {len(r.json().get('series', []))} bars")
        elif r.status_code == 429:
            print(f"{month}: concurrency limit — wait for current requests")
        else:
            print(f"{month}: error {r.status_code}")
\`\`\``,
  },
  {
    uri: "insightsentry://docs/futures-history",
    name: "InsightSentry Futures History Guide",
    description: "How to fetch extensive historical data for futures contracts, including contract month logic",
    mimeType: "text/markdown",
    content: `# Futures Historical Data Guide

Full documentation: https://insightsentry.com/docs

## 1. Overview

          This guide demonstrates how to fetch historical data for Futures contracts.
            The example below uses NASDAQ Futures (NQ) to illustrate how to handle contract month logic, date ranges, and pagination.

          Note that continuous futures do not support more than 1 year of historical data. Therefore, for extensive Futures history, you must use specific contracts. This guide explains how to fetch data for each individual contract.






#### Important Caution

                Currently, concurrent requests are not encouraged and may fail.
                  Please run requests sequentially as demonstrated in this script.
                  This code is for demonstration purposes and provides a basic implementation.










## 2. Implementation



          The following Python script demonstrates how to iterate through contract months and fetch minute-level data.
            While this example targets NASDAQ Futures, the same logic applies to other futures contracts with appropriate adjustments to contract months and symbols.

          The script will create a \`data\` directory and save JSON files organized by symbol and date.
            You can also store the data in SQL database or in different format.



              \`import os
import json
import time
import requests
from datetime import datetime

BASE_URL = 'https://api.insightsentry.com'
START_YEAR = 2025
BASE_SYMBOL_PREFIX = 'CME_MINI:NQ'
BASE_CONTRACTS = ['H', 'M', 'U', 'Z']
API_KEY = 'YOUR_KEY'

def get_contract_months(contract, year):

            datetime(year - 1, 12, 1),
            datetime(year, 1, 1),
            datetime(year, 2, 1),
            datetime(year, 3, 1),

    elif contract == 'M':

            datetime(year, 3, 1),
            datetime(year, 4, 1),
            datetime(year, 5, 1),
            datetime(year, 6, 1),

    elif contract == 'U':

            datetime(year, 6, 1),
            datetime(year, 7, 1),
            datetime(year, 8, 1),
            datetime(year, 9, 1),

    elif contract == 'Z':

            datetime(year, 9, 1),
            datetime(year, 10, 1),
            datetime(year, 11, 1),
            datetime(year, 12, 1),

def fetch_and_save(symbol_code, start_date):
    base_dir = f'./data/{BASE_SYMBOL_PREFIX}'
    date_str = start_date.strftime('%Y-%m-%d')
    file_path = f'{base_dir}/{symbol_code}/{date_str}.json'

        print(f'Already exists: {date_str}')

    os.makedirs(os.path.dirname(file_path), exist_ok=True)

    data = get_ohlcv(symbol_code, start_date)

        series_len = len(data.get('series', []))
        print(f"Symbol: {symbol_code} | Date: {start_date} | Bars: {series_len} bars")
        with open(file_path, 'w') as f:
            json.dump(data, f)

def get_ohlcv(symbol_code, start_date):
    # timeformat is YYYY-MM for minute and hour
    formatted_start_date_str = start_date.strftime('%Y-%m')

    retry_counter = 0
    while retry_counter < 5:
        result = _fetch(symbol_code, formatted_start_date_str)

        print(f'Failed to fetch data for {symbol_code} | Date: {start_date} | Retrying... ({retry_counter}) ')
        retry_counter += 1
        time.sleep(retry_counter * 0.5)

def _fetch(symbol_code, formatted_start_date_str):

        url = f'{BASE_URL}/v3/symbols/{symbol_code}/history'
        params = {
            'bar_interval': '1',
            'bar_type': 'minute',
            'start_date': formatted_start_date_str,

        headers = {
            'Authorization': f'Bearer {API_KEY}',
            'Content-Type': 'application/json'

        response = requests.get(url, params=params, headers=headers, timeout=120)

                print(response.text)
                response.raise_for_status()

            data = response.json()

                print(data)
                raise Exception(data.get('message') or data.get('error'))

            print(response.text)

    except requests.exceptions.RequestException as e:

                raise e
        print(e)

    except Exception as e:
        print(e)

def main():
    current_year = datetime.now().year

    for year in range(START_YEAR, current_year + 1):
        for contract in BASE_CONTRACTS:
            symbol_code = f'{BASE_SYMBOL_PREFIX}{contract}{year}'
            months = get_contract_months(contract, year)

            for start_date in months:

                    continue

                print(f"Fetching data for {symbol_code} for {start_date.strftime('%Y-%m-%d')}")
                fetch_and_save(symbol_code, start_date)

    main()\``,
  }
];
